remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
title: "Working On It"
name: "Bryan Bai"
author:
  name   : "Your Name"
  avatar : "/assets/img/me.png"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  email  : "byebyebryan@gmail.com"
  uri    : "https://byebyebryan.com"
  home   : # null (default), "absolute or relative url to link to author home"