title: Bryan
description: Games, graphics, and AI tooling.
url: https://dev.byebyebryan.com
baseurl: ""
github_username: byebyebryan

permalink: /:categories/:year/:month/:day/:title/
markdown: kramdown
timezone: America/Los_Angeles

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Bryan

theme: null
plugins:
  - jekyll-feed
